# Generated By ChatGpt
import matplotlib.pyplot as plt
from datetime import datetime

def read_log_file(filename):
    times = []
    temperatures = []
    with open(filename, "r") as file:
        for line in file:
            time_str, temperature_str = line.strip().split()
            time = datetime.strptime(time_str[1:-1], "%H:%M:%S")
            temperature = int(temperature_str)
            times.append(time)
            temperatures.append(temperature)
    return times, temperatures

filenames = [
    "../thermal/thermal_zone0",
    "../thermal/thermal_zone5",
    "../thermal/thermal_zone6",
    "../thermal/thermal_zone7"
]

current_zone_index = 0

fig, ax = plt.subplots(figsize=(10, 6))
times, temperatures = read_log_file(filenames[current_zone_index])
line, = ax.plot(times, temperatures, linestyle='None', marker='o')
ax.set_title(f'CPU Temperature Over Time ({filenames[current_zone_index].split("/")[-1]})')
ax.set_xlabel('Time')
ax.set_ylabel('Temperature')
ax.grid(True)

# navigate through graphs
def on_key(event):
    global current_zone_index
    if event.key == 'right':
        current_zone_index = (current_zone_index + 1) % len(filenames)
    elif event.key == 'left':
        current_zone_index = (current_zone_index - 1) % len(filenames)
    times, temperatures = read_log_file(filenames[current_zone_index])
    line.set_xdata(times)
    line.set_ydata(temperatures)
    ax.set_title(f'CPU Temperature Over Time ({filenames[current_zone_index].split("/")[-1]})')
    fig.canvas.draw()

# Connect the event handler
fig.canvas.mpl_connect('key_press_event', on_key)

plt.show()
